M48
; DRILL file {KiCad 9.0.1} date 2025-04-23T11:08:12-0400
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2025-04-23T11:08:12-04:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,9.0.1
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.600
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C2.200
%
G90
G05
T1
X36.0Y-25.77
X41.78Y-25.77
T2
X24.0Y-24.0
X24.0Y-136.0
X176.0Y-24.0
X176.0Y-136.0
M30
